#!/bin/bash
# sync-assets.sh - 从 Flask 仓库复制静态前端资源到 www/ 目录
# 用法: SUANMING_SOURCE=/path/to/suanming bash scripts/sync-assets.sh
#   或: bash scripts/sync-assets.sh （默认使用 /root/suanming）

set -e

SOURCE="${SUANMING_SOURCE:-/root/suanming}"
DEST="www"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

cd "$PROJECT_DIR"

if [ ! -d "$SOURCE" ]; then
    echo "Error: Source directory not found: $SOURCE"
    echo "Set SUANMING_SOURCE environment variable or clone the repo first."
    exit 1
fi

echo "Syncing assets from $SOURCE to $DEST ..."

# Clean www/
rm -rf "$DEST"
mkdir -p "$DEST"

# Copy top-level HTML files
echo "  Copying HTML files ..."
cp "$SOURCE"/*.html "$DEST/" 2>/dev/null || true

# Copy icon
if [ -f "$SOURCE/icon-192.png" ]; then
    cp "$SOURCE/icon-192.png" "$DEST/"
fi

# Copy manifest
if [ -f "$SOURCE/manifest.json" ]; then
    cp "$SOURCE/manifest.json" "$DEST/"
fi

# Copy CSS directory
echo "  Copying CSS ..."
cp -r "$SOURCE/css" "$DEST/"

# Copy JS directory
echo "  Copying JS ..."
cp -r "$SOURCE/js" "$DEST/"

# Copy modules directory
echo "  Copying modules/ ..."
cp -r "$SOURCE/modules" "$DEST/"

# Copy static directory (avatars etc) if exists
if [ -d "$SOURCE/static" ]; then
    echo "  Copying static/ ..."
    cp -r "$SOURCE/static" "$DEST/"
fi

# ---- Generate www/js/api-config.js ----
echo "  Generating api-config.js ..."
cat > "$DEST/js/api-config.js" << 'APIEOF'
// Auto-generated by sync-assets.sh — do not edit
(function() {
  // Production API base URL for Capacitor native app
  window.__API_BASE__ = 'https://xuanjisuanming.top';

  // Dev override: if running in local browser, use localhost
  if (window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1') {
    window.__API_BASE__ = 'http://localhost:5000';
  }
})();
APIEOF

# ---- Copy capacitor-init.js from src/js/ ----
if [ -f "$PROJECT_DIR/src/js/capacitor-init.js" ]; then
    cp "$PROJECT_DIR/src/js/capacitor-init.js" "$DEST/js/capacitor-init.js"
    echo "  Copied capacitor-init.js"
fi

# ---- Summary ----
HTML_COUNT=$(find "$DEST" -maxdepth 1 -name "*.html" | wc -l)
MODULE_COUNT=$(find "$DEST/modules" -name "*.html" 2>/dev/null | wc -l)
JS_COUNT=$(find "$DEST/js" -name "*.js" | wc -l)
CSS_COUNT=$(find "$DEST/css" -name "*.css" | wc -l)

echo ""
echo "Sync complete!"
echo "  HTML pages: $HTML_COUNT"
echo "  Module pages: $MODULE_COUNT"
echo "  JS files: $JS_COUNT"
echo "  CSS files: $CSS_COUNT"
